2-D ARRAY

In [2]:
import numpy as np

CREATING A LIST

In [3]:
ls = [[12,23,1],[24,45,2],[45,56,3]]

STORING IT IN ARRAY

In [4]:
arr2 = np.array(ls)
arr2

array([[12, 23,  1],
       [24, 45,  2],
       [45, 56,  3]])

In [5]:
arr2.ndim

2

In [6]:
arr2.shape

(3, 3)

In [7]:
arr2[0]

array([12, 23,  1])

In [8]:
arr2[2]

array([45, 56,  3])

In [9]:
arr2[0:2]

array([[12, 23,  1],
       [24, 45,  2]])

DEFINING ROW AND COLUMN ROW=1 TO LAST AND COLUMN=1 TO LAST

In [10]:
arr2[1:,1:]

array([[45,  2],
       [56,  3]])

In [11]:
arr2[1:3,1:3]

array([[45,  2],
       [56,  3]])

In [12]:
arr2[0:2,1:3]

array([[23,  1],
       [45,  2]])

In [13]:
arr2

array([[12, 23,  1],
       [24, 45,  2],
       [45, 56,  3]])

In [14]:
arr2[-2:,]

array([[24, 45,  2],
       [45, 56,  3]])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.linspace(1,50,10)
#array between 1 to 50 and consist of 10 items

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [18]:
#3D array
ls =[[[1,2,3],[12,23,34],[23,1,2]],
     [[2,5,6],[7,8,9],[3,5,6]],
     [[1,2,3],[4,5,6],[7,8,9]]]

In [19]:
arr3=np.array(ls)

In [20]:
arr3.ndim

3

In [21]:
arr3.shape

(3, 3, 3)

In [22]:
arr3

array([[[ 1,  2,  3],
        [12, 23, 34],
        [23,  1,  2]],

       [[ 2,  5,  6],
        [ 7,  8,  9],
        [ 3,  5,  6]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]]])

In [23]:
arr3[2]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr3[:,1:,1:]

array([[[23, 34],
        [ 1,  2]],

       [[ 8,  9],
        [ 5,  6]],

       [[ 5,  6],
        [ 8,  9]]])

In [25]:
arr3.shape


(3, 3, 3)

In [26]:
arr3.flatten

<function ndarray.flatten>

In [28]:
arr3.reshape(27,)

array([ 1,  2,  3, 12, 23, 34, 23,  1,  2,  2,  5,  6,  7,  8,  9,  3,  5,
        6,  1,  2,  3,  4,  5,  6,  7,  8,  9])