IMPORTING NUMPY

In [2]:
import numpy as np 

CHECKING NUMPY VERSION

In [3]:
np.__version__

'2.0.1'

NUMPY IS USED FOR CREATING ARRAY AND FUNCTIONS ON ARRAYS AND STRINGS

1-D ARRAY

In [4]:
ls = [25,10,20,30,40,50,60]
arr = np.array([25,10,20,30,40,50,60])
arr


array([25, 10, 20, 30, 40, 50, 60])

In [5]:
# type(ls)
type(arr)

numpy.ndarray

In [6]:
arr.ndim

1

In [7]:
arr.size

7

In [8]:
len(arr)

7

In [9]:
arr.shape

(7,)

In [10]:
arr.dtype

dtype('int64')

In [11]:
arr = np.array([25,10,20,30,40,50,'hello'])
arr
arr.dtype

dtype('<U21')

In [12]:
arr = np.array([25,10,20,30,40,50,23.4])
arr
arr.dtype

dtype('float64')

In [13]:
arr = np.array([25,10,20,30,40,50,])
arr
arr.dtype

dtype('int64')

In [14]:
arr = np.array([25,34,4,6,67,56,67])
arr[4:]

array([67, 56, 67])

In [15]:
arr/5

array([ 5. ,  6.8,  0.8,  1.2, 13.4, 11.2, 13.4])

In [16]:
min(arr)

np.int64(4)

In [17]:
max(arr)

np.int64(67)

In [18]:
sum(arr)

np.int64(259)

In [19]:
np.mean(arr)

np.float64(37.0)

In [20]:
np.median(arr)

np.float64(34.0)

np.mode(arr) #numpy does not consist of mode function

In [22]:
import random #numpy consist of random module

In [23]:
random.randint(1,9)

5

In [24]:
arr = np.random.randint(1,450,500)
arr

array([152, 165,  35,  64, 120,  49,  92,  83, 428, 186, 155, 236, 415,
       136,  27, 334,  59, 166, 266, 262, 432, 243, 380, 373,  24,  58,
       106, 169,   8, 212, 336, 308,  53, 431, 313, 352, 448, 251, 228,
       424, 309, 122,  64,  73,  97, 222, 314, 276, 173,  78, 121, 227,
        32, 210, 341, 130,  29, 449, 313,  42, 382, 409, 173, 178, 372,
        86, 182, 277, 336, 198, 375, 239, 399, 127, 353,  43, 267, 245,
       314, 403, 146, 240, 198, 108,  83, 164, 415, 412, 141, 402, 210,
       315,  70, 387,  67, 238,   2, 249,  41, 323, 353, 287, 332, 341,
       122, 193, 175, 363, 167, 190, 153,  87,  90, 446, 396, 257, 355,
       256,  61, 327, 182, 277, 286, 360,  94,  70, 404, 248, 122, 326,
       410,  87, 223, 277, 176, 389, 200, 306,  87,  96, 276, 365,  31,
       226, 118,  62, 229,  85, 420,  53, 319,  59,  54, 435, 441, 246,
       447,  46,  78, 274, 330, 211, 411, 364,  56, 276, 437, 366,  84,
       214, 121, 116, 366, 437, 187,   4, 431, 147, 392, 283, 13

In [25]:
import random, string

In [26]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [28]:
alpha=string.ascii_letters +string.digits
alpha

'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'

In [30]:
x=random.choice
x

<bound method Random.choice of <random.Random object at 0x000001A3A189AE60>>

In [31]:
arr = np.random.randint(1,450,500)
arr
#calculate no of even count
#calculate items that are less than 100

array([159, 329, 428, 200, 415, 268, 376, 232, 333, 262, 111,  60, 181,
       221,  38,  92,  85, 424, 221, 400, 199, 323, 259,  21, 383, 446,
       347, 414,  20, 223, 287, 297, 172, 275, 419, 101,  30, 415, 226,
       223,  63, 361,  61, 267, 125, 315, 287, 386,  52,  62, 239, 241,
       293, 399, 289, 390, 288, 430, 183, 171,   7, 203, 433, 268, 257,
        76, 115, 273, 396, 425, 133, 256, 444, 426,  45, 213, 260,  48,
         5, 441, 392,  25, 369,  67, 436, 270, 306, 263, 250, 200, 104,
       219, 285, 209, 136, 190, 364, 435,  49, 391, 260, 278,  62,  76,
       406, 437, 386, 267, 297, 104, 386, 411,  61,  49, 414, 225, 188,
        55,  65, 341,  56, 300, 426, 378, 379, 185,  24, 240, 379, 245,
       267,  81, 125, 366, 140, 192,  15, 442, 339, 356, 187, 251, 109,
        56, 246, 320,  24,  77, 106, 373, 117, 448, 208, 339, 419, 167,
         5, 151, 365,  15, 321, 335, 232, 438, 142, 325, 317,  86,  11,
       187, 296, 103, 231, 349, 395,  17, 246,  44,   2,  10,  1

In [33]:
y=sum(arr < 100)
y

np.int64(101)

In [34]:
arr[arr<100]

array([60, 38, 92, 85, 21, 20, 30, 63, 61, 52, 62,  7, 76, 45, 48,  5, 25,
       67, 49, 62, 76, 61, 49, 55, 65, 56, 24, 81, 15, 56, 24, 77,  5, 15,
       86, 11, 17, 44,  2, 10, 13, 95, 15,  9,  3, 75, 58, 35, 56, 92, 70,
       50, 83, 37, 64,  1, 13, 88, 19, 14, 18, 56,  6, 55,  5, 83, 83, 54,
       34, 88, 43, 69,  6, 80, 18, 56, 47, 19,  6, 44, 45, 32, 27,  8, 60,
       95, 25, 80, 94,  2, 18, 80, 13, 51, 29, 39, 49, 66, 20, 22,  9],
      dtype=int32)

In [35]:
len(arr[arr < 100])

101